# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMIcalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(240, 190)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(240, 190))
        mainWindow.setMaximumSize(QtCore.QSize(240, 190))
        self.mainWidget = QtWidgets.QWidget(mainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.calculateButton = QtWidgets.QPushButton(self.mainWidget)
        self.calculateButton.setGeometry(QtCore.QRect(10, 60, 220, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculateButton.sizePolicy().hasHeightForWidth())
        self.calculateButton.setSizePolicy(sizePolicy)
        self.calculateButton.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.calculateButton.setIconSize(QtCore.QSize(16, 16))
        self.calculateButton.setShortcut("")
        self.calculateButton.setAutoDefault(False)
        self.calculateButton.setDefault(True)
        self.calculateButton.setFlat(False)
        self.calculateButton.setObjectName("calculateButton")
        self.massInput = QtWidgets.QLineEdit(self.mainWidget)
        self.massInput.setGeometry(QtCore.QRect(130, 10, 100, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.massInput.sizePolicy().hasHeightForWidth())
        self.massInput.setSizePolicy(sizePolicy)
        self.massInput.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";")
        self.massInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.massInput.setInputMask("")
        self.massInput.setText("")
        self.massInput.setMaxLength(5)
        self.massInput.setObjectName("massInput")
        self.BMIoutput = QtWidgets.QTextBrowser(self.mainWidget)
        self.BMIoutput.setGeometry(QtCore.QRect(59, 120, 121, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BMIoutput.sizePolicy().hasHeightForWidth())
        self.BMIoutput.setSizePolicy(sizePolicy)
        self.BMIoutput.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";")
        self.BMIoutput.setObjectName("BMIoutput")
        self.heightInput = QtWidgets.QLineEdit(self.mainWidget)
        self.heightInput.setGeometry(QtCore.QRect(10, 10, 100, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightInput.sizePolicy().hasHeightForWidth())
        self.heightInput.setSizePolicy(sizePolicy)
        self.heightInput.setAutoFillBackground(False)
        self.heightInput.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";")
        self.heightInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.heightInput.setInputMask("")
        self.heightInput.setText("")
        self.heightInput.setMaxLength(5)
        self.heightInput.setObjectName("heightInput")
        mainWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "BMI Calculator"))
        self.calculateButton.setText(_translate("mainWindow", "Calculate!"))
        self.massInput.setPlaceholderText(_translate("mainWindow", "Mass (Kg)"))
        self.BMIoutput.setPlaceholderText(_translate("mainWindow", "BMI"))
        self.heightInput.setPlaceholderText(_translate("mainWindow", "Height(m)"))
